trigger:
  branches:
    include:
      - master

pool:
  name: default

stages:
- stage: Build
  displayName: 'Build Docker image'
  jobs:
  - job: BuildJob
    displayName: 'Build and Push'
    steps:
    - checkout: self
    
    - script: |
        docker logout
        docker login -u "ashfaqbarkati786" -p "Ashfaq@123"
      displayName: 'Login to Docker Hub'

    - script: |
        docker build -t ashfaqbarkati786/flask1:$(Build.BuildId) -f Dockerfile .
        docker push ashfaqbarkati786/flask1:$(Build.BuildId)
      displayName: 'Build and Push Docker Image'
    

- stage: Deploy
  displayName: 'Deploy Infrastructure'
  dependsOn: Build
  jobs:
  - job: TerraformJob
    displayName: 'Terraform Deployment'
    steps:
    - checkout: self

    - task: CmdLine@2
      displayName: 'Run Terraform'
      inputs:
        script: |
          cd $(Build.SourcesDirectory)/terraformfiles  
          terraform init    
          terraform plan
          terraform apply -auto-approve


    
    - script: |
          az aks get-credentials --resource-group Final-Project --name aks --overwrite-existing
      displayName: 'Get AKS Cluster Credentials'
      
    - script: |
        kubectl get nodes
      displayName: 'Verify AKS Cluster Connection'


    - script: |
        export IMAGE_TAG=$(Build.BuildId)
        envsubst '${IMAGE_TAG}' < deployments/webapp-deployment.yaml > deployments/webapp-deployment-modified.yaml
        kubectl apply -f deployments/webapp-deployment-modified.yaml
        kubectl apply -f deployments/
      displayName: 'Replace Environment Variables and Deploy to AKS Cluster'